### ISSUE TITLE
error tried to allocate >=1 mb memory; aborted 

### ISSUE THREAD

**Issue by Ivy101D** [SteffenL/dead-island-save-editor#21]
I keep getting this error when I do open from USB device ps3.  I have gotten this message from 2 usb devices and I'm trying to edit a save for Riptide I have looked around and I'm not the only one with this issue I just haven't found a solution. 
![20200504_204527](https://user-images.githubusercontent.com/64816998/81026495-4f73cc80-8e48-11ea-895a-9073179948f0.jpg)

**Comment by SteffenL** [comment]
Thanks for reporting this. This happened after open-sourcing DISE since I removed a lot of secret files without testing PS3 support afterwards.

You can use [version 0.2.0-dev+g8845772](https://builds.steffenl.com/download/dise/0.2.0-dev%2bg8845772/dise-0.2.0-dev%2bg8845772-setup.exe) until this is fixed.

**Comment by Ivy101D** [comment]
Thank you
